//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _300936630_Mizubuchi__Test1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionHistory
    {
        public string AccountNo { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime TransactionTime { get; set; }
        public Nullable<int> BranchID { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
